FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app/bot

COPY requirements.txt /app/bot/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

# # Установка PostgreSQL и утилиты pg_dump и еще разной мути..
RUN apt-get update && apt-get install -y apt-utils \
    postgresql \
    postgresql-contrib \
    postgresql-client 

COPY . .

CMD ["python", "app/bot.py"]