"""Description of changes

Revision ID: 8026cbeb346a
Revises: 
Create Date: 2024-04-09 03:29:30.487387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8026cbeb346a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms_id',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title_room', sa.String(length=500), nullable=True),
    sa.Column('name_room', sa.String(length=500), nullable=True),
    sa.Column('type_house', sa.String(length=500), nullable=True),
    sa.Column('night_price', sa.Float(), server_default='0', nullable=False),
    sa.Column('month_price', sa.Float(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('guest_favorite', sa.Float(), nullable=True),
    sa.Column('guest', sa.Integer(), nullable=True),
    sa.Column('bedroom', sa.Integer(), nullable=True),
    sa.Column('bed', sa.Integer(), nullable=True),
    sa.Column('bath', sa.Float(), nullable=True),
    sa.Column('parking', sa.String(length=500), nullable=True),
    sa.Column('kitchen', sa.String(length=500), nullable=True),
    sa.Column('view', sa.String(length=500), nullable=True),
    sa.Column('workspace', sa.String(length=500), nullable=True),
    sa.Column('rooftop', sa.String(length=500), nullable=True),
    sa.Column('terrace_balcony', sa.String(length=500), nullable=True),
    sa.Column('restaurants', sa.String(length=500), nullable=True),
    sa.Column('storage', sa.String(length=500), nullable=True),
    sa.Column('sqm', sa.String(length=500), nullable=True),
    sa.Column('url_room', sa.String(length=2000), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('obj_date_update', sa.DateTime(), nullable=True),
    sa.Column('list_date_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id_id'), 'rooms_id', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('date_reg', sa.DateTime(), nullable=True),
    sa.Column('date_visit', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_block', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('checkin_date', sa.DateTime(), nullable=True),
    sa.Column('checkout_date', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(length=100), server_default='Bali', nullable=False),
    sa.Column('guest', sa.Integer(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name_task', sa.String(length=100), nullable=True),
    sa.Column('date_task', sa.DateTime(), nullable=True),
    sa.Column('data_task', sa.String(length=3000), nullable=True),
    sa.Column('owner_task', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner_task'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'owner_task')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rooms_id_id'), table_name='rooms_id')
    op.drop_table('rooms_id')
    # ### end Alembic commands ###
