"""Description of changes

Revision ID: 9eae5450c054
Revises: 
Create Date: 2024-04-13 00:57:36.318846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eae5450c054'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airbnb',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=5000), nullable=False),
    sa.Column('title', sa.String(length=3000), nullable=True),
    sa.Column('name', sa.String(length=3000), nullable=True),
    sa.Column('type_house', sa.String(length=3000), nullable=True),
    sa.Column('night_price', sa.Float(), server_default='0', nullable=False),
    sa.Column('month_price', sa.Float(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('guest_favorite', sa.Float(), nullable=True),
    sa.Column('guest', sa.Integer(), nullable=True),
    sa.Column('bedroom', sa.Integer(), nullable=True),
    sa.Column('bed', sa.Integer(), nullable=True),
    sa.Column('bath', sa.Float(), nullable=True),
    sa.Column('parking', sa.String(length=3000), nullable=True),
    sa.Column('kitchen', sa.String(length=3000), nullable=True),
    sa.Column('view', sa.String(length=3000), nullable=True),
    sa.Column('workspace', sa.String(length=3000), nullable=True),
    sa.Column('rooftop', sa.String(length=3000), nullable=True),
    sa.Column('terrace_balcony', sa.String(length=3000), nullable=True),
    sa.Column('restaurants', sa.String(length=3000), nullable=True),
    sa.Column('storage', sa.String(length=3000), nullable=True),
    sa.Column('sqm', sa.String(length=3000), nullable=True),
    sa.Column('location', sa.String(length=3000), nullable=False),
    sa.Column('date_update', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airbnb_id'), 'airbnb', ['id'], unique=True)
    op.create_table('airdna',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('revenue_ltm', sa.BigInteger(), nullable=True),
    sa.Column('revenue_potential_ltm', sa.BigInteger(), nullable=True),
    sa.Column('occupancy_rate_ltm', sa.Float(), nullable=True),
    sa.Column('average_daily_rate_ltm', sa.BigInteger(), nullable=True),
    sa.Column('days_available_ltm', sa.BigInteger(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airdna_id'), 'airdna', ['id'], unique=True)
    op.create_table('id',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=5000), nullable=False),
    sa.Column('busy_flag', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('passed_flag', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_id_id'), 'id', ['id'], unique=True)
    op.create_table('point',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('price_min', sa.Integer(), server_default='10', nullable=False),
    sa.Column('price_max', sa.Integer(), server_default='11', nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('date_reg', sa.DateTime(), nullable=True),
    sa.Column('date_visit', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_block', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('time_correction', sa.Integer(), server_default='+5', nullable=False),
    sa.Column('checkin_date', sa.DateTime(), nullable=True),
    sa.Column('checkout_date', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(length=3000), server_default='Bali', nullable=False),
    sa.Column('guest', sa.Integer(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name_task', sa.String(length=3000), nullable=True),
    sa.Column('date_task', sa.DateTime(), nullable=True),
    sa.Column('data_task', sa.String(length=3000), nullable=True),
    sa.Column('owner_task', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner_task'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'owner_task')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('point')
    op.drop_index(op.f('ix_id_id'), table_name='id')
    op.drop_table('id')
    op.drop_index(op.f('ix_airdna_id'), table_name='airdna')
    op.drop_table('airdna')
    op.drop_index(op.f('ix_airbnb_id'), table_name='airbnb')
    op.drop_table('airbnb')
    # ### end Alembic commands ###
